ARG GO_VER=1.18
ARG ALPINE_VER=3.14

FROM golang:${GO_VER}-alpine${ALPINE_VER} as build

# Use aliyun apk repository to make image build faster
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
RUN apk add --no-cache \
	bash \
	binutils-gold \
    dumb-init \
	gcc \
	git \
	make \
	musl-dev

ADD . $GOPATH/go-contract
WORKDIR $GOPATH/go-contract

ENV GOPROXY=https://goproxy.cn,direct
RUN go mod tidy
RUN rm -r $GOPATH/go-contract